#!/bin/bash

ARCH=x86_64
VERSIONS="4.9 4.10 4.11 4.12 4.13 4.14 4.15 4.16"

for v in $VERSIONS; do
    scripts/build-kernel-version $v $ARCH
    if [ "$?" != "0" ]; then
        echo "Build on $v kernel FAILED"
        exit 255
    fi
done
