#!/bin/bash

ARCH=x86_64
VERSIONS="4.10 4.14"

for v in $VERSIONS; do
    scripts/build-kernel-version $v $ARCH
    if [ "$?" != "0" ]; then
        echo "Build on $v kernel FAILED"
        exit 255
    fi
done
