#!/usr/bin/env python

# Written by: Vincenzo Maffione <v.maffione@gmail.com>

from rlite import *
import argparse
import select
import sys
import os


def python2():
    return sys.version_info[0] <= 2


def str2buf(s):
    if python2():
        return s
    return bytes(s, 'ascii')


def buf2str(b):
    if python2():
        return b
    return b.decode('ascii')


class RinaRRTool(RliteCtrl):

    def __init__(self):
        RliteCtrl.__init__(self)
        self.client_name = RinaName()
        self.server_name = RinaName()
        self.dif = ""
        self.flow_spec = RliteFlowSpec()


    def client(self, args):
        fd = self.flow_alloc(self.dif, self.client_name,
                             self.server_name, self.flow_spec)
        if fd < 0:
            return fd

        msg = 'Hello guys, this is a test message!'
        n = os.write(fd, str2buf(msg))
        if n != len(msg):
            print("Partial write %s/%s", n, len(msg))

        r, w, e = select.select([fd], [], [], 3000)
        if len(r) == 0:
            print("Timeout")
            return -1

        buf = os.read(fd, 65535)
        print("Response: '%s'" % buf2str(buf))

        os.close(fd)

        return 0


    def server(self, args):
        self.register(self.dif, self.server_name)

        while 1:
            fd = self.flow_accept()
            if fd < 0:
                continue

            r, w, e = select.select([fd], [], [], 3000)
            if len(r) == 0:
                print("Timeout")
                return -1

            buf = os.read(fd, 65535)
            print("Request: '%s'" % buf2str(buf))

            n = os.write(fd, buf)
            if n != len(buf):
                print("Partial write %s/%s", n, len(buf))

            os.close(fd)

        return 0


description = "RINA echo client/server"
epilog = "2015-2016 Vincenzo Maffione <v.maffione@gmail.com>"

argparser = argparse.ArgumentParser(description = description,
                                    epilog = epilog)
argparser.add_argument('-l', '--listen', dest = 'server_mode',
                       action='store_true',
                       help = "Run in server mode")
argparser.add_argument('-d', '--dif',
                       help = "DIF to register to or ask for flow allocation",
                       type = str)
argparser.add_argument('-f', '--flow-spec', help = "Flow specification",
                       type = str, default='unrel')
argparser.add_argument('-a', '--client-apn', help = "client APN",
                       type = str, default='rl_rr-data')
argparser.add_argument('-A', '--client-api', help = "client API",
                       type = str, default='client')
argparser.add_argument('-z', '--server-apn', help = "server APN",
                       type = str, default='rl_rr-data')
argparser.add_argument('-Z', '--server-api', help = "server API",
                       type = str, default='server')

args = argparser.parse_args()

try:
    rr = RinaRRTool()

    rr.client_name = RinaName(args.client_apn, args.client_api, None, None)
    rr.server_name = RinaName(args.server_apn, args.server_api, None, None)
    rr.dif = args.dif
    rr.flow_spec = RliteFlowSpec(args.flow_spec)

    if args.server_mode:
        rr.server(args)
    else:
        rr.client(args)
except KeyboardInterrupt:
    pass
