#!/usr/bin/env python

# Written by: Vincenzo Maffione <v.maffione@gmail.com>

import argparse
import select
import rlite
import sys
import os


def python2():
    return sys.version_info[0] <= 2


def str2buf(s):
    if python2():
        return s
    return bytes(s, 'ascii')


def buf2str(b):
    if python2():
        return b
    return b.decode('ascii')


class RinaRRTool:

    def __init__(self):
        self.cfd = rlite.open()
        if self.cfd < 0:
            raise Exception("Could not open rlite ctrl device")

        self.client_name = ''
        self.server_name = ''
        self.dif = ''
        self.flow_spec = rlite.flow_spec()
        rlite.flow_spec_default(self.flow_spec)


    def __del__(self):
        os.close(self.cfd)


    def client(self, args):
        fd = rlite.flow_alloc(self.dif, self.client_name,
                              self.server_name, self.flow_spec, 0)

        if fd < 0:
            return fd

        msg = 'Hello guys, this is a test message!'
        n = os.write(fd, str2buf(msg))
        if n != len(msg):
            print("Partial write %s/%s", n, len(msg))

        r, w, e = select.select([fd], [], [], 3000)
        if len(r) == 0:
            print("Timeout")
            return -1

        buf = os.read(fd, 65535)
        print("Response: '%s'" % buf2str(buf))

        os.close(fd)

        return 0


    def server(self, args):
        ret = rlite.register(self.cfd, self.dif, self.server_name)
        if ret:
            return ret

        while 1:
            fd = rlite.flow_accept(self.cfd, None, 0)
            if fd < 0:
                continue

            r, w, e = select.select([fd], [], [], 3000)
            if len(r) == 0:
                print("Timeout")
                return -1

            buf = os.read(fd, 65535)
            print("Request: '%s'" % buf2str(buf))

            n = os.write(fd, buf)
            if n != len(buf):
                print("Partial write %s/%s", n, len(buf))

            os.close(fd)

        return 0


description = "RINA echo client/server (raw API version)"
epilog = "2015-2016 Vincenzo Maffione <v.maffione@gmail.com>"

argparser = argparse.ArgumentParser(description = description,
                                    epilog = epilog)
argparser.add_argument('-l', '--listen', dest = 'server_mode',
                       action='store_true',
                       help = "Run in server mode")
argparser.add_argument('-d', '--dif',
                       help = "DIF to register to or ask for flow allocation",
                       type = str)
argparser.add_argument('-a', '--client-name', help = "client name",
                       type = str, default='rl_rr-data/client')
argparser.add_argument('-z', '--server-name', help = "server name",
                       type = str, default='rl_rr-data/server')

args = argparser.parse_args()

try:
    rr = RinaRRTool()

    rr.client_name = args.client_name
    rr.server_name = args.server_name
    rr.dif = args.dif

    if args.server_mode:
        rr.server(args)
    else:
        rr.client(args)
except KeyboardInterrupt:
    pass
